# Generated by Django 5.1.6 on 2025-02-21 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassCoordinator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("section", models.CharField(blank=True, max_length=10, null=True)),
                ("coordinator_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("section", models.CharField(blank=True, max_length=10, null=True)),
                ("status", models.CharField(max_length=20)),
                ("doctor_notes", models.TextField()),
                ("date_reported", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("departure_time", models.DateTimeField()),
                ("return_time", models.DateTimeField()),
                ("reject", models.BooleanField(default=False)),
                ("hod_approval", models.BooleanField(default=False)),
                ("warden_approval", models.BooleanField(default=False)),
                ("security_verification", models.BooleanField(default=False)),
                ("final_status", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
