# Generated by Django 5.1.6 on 2025-02-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auto_Leave", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classcoordinator",
            name="department",
            field=models.CharField(
                choices=[
                    ("Admin", "Administration"),
                    ("CSE", "Computer Science and Engineering"),
                    ("ECE", "Electronics and Communication Engineering"),
                    ("EEE", "Electrical and Electronics Engineering"),
                    ("ME", "Mechanical Engineering"),
                    ("CE", "Civil Engineering"),
                    ("IT", "Information Technology"),
                    ("Mathematics", "Mathematics"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="department",
            field=models.CharField(
                choices=[
                    ("Admin", "Administration"),
                    ("CSE", "Computer Science and Engineering"),
                    ("ECE", "Electronics and Communication Engineering"),
                    ("EEE", "Electrical and Electronics Engineering"),
                    ("ME", "Mechanical Engineering"),
                    ("CE", "Civil Engineering"),
                    ("IT", "Information Technology"),
                    ("Mathematics", "Mathematics"),
                ],
                max_length=100,
            ),
        ),
    ]
