# Generated by Django 5.1.6 on 2025-02-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auto_Leave", "0002_alter_classcoordinator_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthrecord",
            name="full_name",
            field=models.CharField(default="not found", max_length=20),
        ),
    ]
