# Generated by Django 5.1.6 on 2025-02-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auto_Leave", "0003_healthrecord_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="proof",
            field=models.ImageField(blank=True, null=True, upload_to="leave_proof/"),
        ),
    ]
