# Generated by Django 5.1.6 on 2025-02-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Auto_Leave", "0004_leaverequest_proof"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HealthRecord",
        ),
    ]
