# Generated by Django 5.1.6 on 2025-02-19 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_uploadedcsv"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("dob", models.DateField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_no", models.CharField(max_length=15)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profiles/faculty/"
                    ),
                ),
                ("designation", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("qualification", models.CharField(max_length=255)),
                ("years_of_experience", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("dob", models.DateField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("registration_no", models.CharField(max_length=100, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("course", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=100)),
                ("year_of_study", models.IntegerField()),
                ("phone_no", models.CharField(max_length=15)),
                ("hostel_status", models.BooleanField()),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profiles/students/"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
