# Generated by Django 5.1.6 on 2025-02-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_facultyprofile_studentprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="custom_user",
            name="department",
            field=models.CharField(
                choices=[
                    ("Admin", "Administration"),
                    ("CSE", "Computer Science and Engineering"),
                    ("ECE", "Electronics and Communication Engineering"),
                    ("EEE", "Electrical and Electronics Engineering"),
                    ("ME", "Mechanical Engineering"),
                    ("CE", "Civil Engineering"),
                    ("IT", "Information Technology"),
                    ("Mathematics", "Mathematics"),
                ],
                default="Admin",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="custom_user",
            name="full_name",
            field=models.CharField(default="empty", max_length=30),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="Parent_phone_no",
            field=models.CharField(default="not found", max_length=15),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="parent_email",
            field=models.EmailField(default="not found", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="custom_user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="custom_user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
        migrations.AlterField(
            model_name="custom_user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("faculty", "Faculty"),
                    ("hod", "Head of Department"),
                    ("dean_student", "Dean of Student"),
                    ("dean_finance", "Dean of Finance"),
                    ("director", "Director"),
                    ("doctor", "Doctor"),
                    ("warden", "Warden"),
                    ("security)", "Security Guard)"),
                    ("admin", "Admin"),
                ],
                max_length=50,
            ),
        ),
    ]
