# Generated by Django 5.1.6 on 2025-02-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0004_custom_user_department_custom_user_full_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facultyprofile",
            name="faculty_coordinator",
            field=models.CharField(default="None", max_length=100),
        ),
    ]
