# Generated by Django 5.1.6 on 2025-02-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0007_alter_custom_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="section",
            field=models.CharField(
                choices=[("B", "B"), ("A", "A")], default="B", max_length=15
            ),
            preserve_default=False,
        ),
    ]
