# Generated by Django 5.1.6 on 2025-02-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0009_alter_custom_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custom_user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("faculty", "Faculty"),
                    ("hod", "Head of Department"),
                    ("sport_head", "Sport Head"),
                    ("dean_student", "Dean of Student"),
                    ("dean_finance", "Dean of Finance"),
                    ("director", "Director"),
                    ("doctor", "Doctor"),
                    ("warden", "Warden"),
                    ("security", "Security Guard"),
                    ("board_member", "Board Member"),
                    ("exam controller", "Exam Controller"),
                    ("admin", "Admin"),
                ],
                max_length=50,
            ),
        ),
    ]
