# Generated by Django 5.1.6 on 2025-02-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Admin", "Administration"),
                            ("CSE", "Computer Science and Engineering"),
                            ("ECE", "Electronics and Communication Engineering"),
                            ("EEE", "Electrical and Electronics Engineering"),
                            ("ME", "Mechanical Engineering"),
                            ("CE", "Civil Engineering"),
                            ("IT", "Information Technology"),
                            ("Mathematics", "Mathematics"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("common", "Common Announcement"),
                            ("result", "Result Declaration"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "pdf",
                    models.FileField(blank=True, null=True, upload_to="announcements/"),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
