# Generated by Django 5.1.6 on 2025-02-22 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Complaints", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cheatingrecord",
            name="reason",
        ),
        migrations.AddField(
            model_name="cheatingrecord",
            name="action",
            field=models.TextField(blank=True, default="Not Done Yet"),
        ),
        migrations.AlterField(
            model_name="cheatingrecord",
            name="student",
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name="ComplaintVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote", models.BooleanField(default=True)),
                (
                    "board_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="Complaints.complaint",
                    ),
                ),
            ],
            options={
                "unique_together": {("complaint", "board_member")},
            },
        ),
    ]
