# Generated by Django 5.1.6 on 2025-02-21 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("login", "0007_alter_custom_user_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("TECHNICAL", "Technical"),
                            ("CULTURAL", "Cultural"),
                            ("SPORTS", "Sports"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("venue", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("approved_by_dean", models.BooleanField(default=False)),
                ("approved_by_director", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "faculty_coordinator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.facultyprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("budget_file", models.FileField(upload_to="budgets/")),
                ("approved_by_dean_finance", models.BooleanField(default=False)),
                ("approved_by_director", models.BooleanField(default=False)),
                ("priority_level", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EventApproval.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sponsorship_file", models.FileField(upload_to="sponsorships/")),
                ("approved_by_dean_finance", models.BooleanField(default=False)),
                ("approved_by_director", models.BooleanField(default=False)),
                ("priority_level", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EventApproval.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RepresentativeStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("TECHNICAL_SECRETARY", "Technical Secretary"),
                            ("GENERAL_SECRETARY", "General Secretary"),
                            ("CULTURAL_SECRETARY", "Cultural Secretary"),
                            ("SPORTS_SECRETARY", "Sports Secretary"),
                            ("CLUB_PRESIDENT", "Club President"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="representative",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="EventApproval.representativestudent",
            ),
        ),
    ]
