# Generated by Django 5.1.6 on 2025-02-22 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("login", "0007_alter_custom_user_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("event_type", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("venue", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("approved_by_dean", models.BooleanField(default=False)),
                ("approved_by_director", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED_BY_DEAN", "Approved by Dean"),
                            ("FINAL_APPROVAL", "Final Approval"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("public_visible", models.BooleanField(default=False)),
                (
                    "faculty_coordinator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinated_events",
                        to="login.facultyprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "budget_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("budget", models.FileField(upload_to="budgets/")),
                ("approved_by_dean_finance", models.BooleanField(default=False)),
                ("approved_by_director", models.BooleanField(default=False)),
                ("priority_level", models.IntegerField(default=0)),
                ("can_edit", models.BooleanField(default=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventbudget",
                        to="EventApproval.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sponsor_name", models.CharField(max_length=200)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("sponsorship_document", models.FileField(upload_to="sponsorships/")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsorships",
                        to="EventApproval.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RepresentativeStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("TECHNICAL_SECRETARY", "Technical Secretary"),
                            ("GENERAL_SECRETARY", "General Secretary"),
                            ("CULTURAL_SECRETARY", "Cultural Secretary"),
                            ("SPORTS_SECRETARY", "Sports Secretary"),
                            ("CLUB_PRESIDENT", "Club President"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="representative",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="EventApproval.representativestudent",
            ),
        ),
    ]
