# Generated by Django 5.1.6 on 2025-02-22 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EventApproval", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventsponsorship",
            name="sponsorship_document",
        ),
        migrations.AddField(
            model_name="eventsponsorship",
            name="sponsorship_details",
            field=models.TextField(default="none"),
        ),
        migrations.AddField(
            model_name="representativestudent",
            name="desig_email",
            field=models.EmailField(default="none", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="eventbudget",
            name="budget",
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name="EventExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="EventApproval.event",
                    ),
                ),
            ],
        ),
    ]
