# Generated by Django 5.1.6 on 2025-02-20 17:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectionPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                ("Eligibility", models.TextField()),
                ("candidate_registration_deadline", models.DateTimeField()),
                ("voting_day", models.DateTimeField()),
                ("dean_approved", models.BooleanField(default=False)),
                ("director_approved", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("registration_number", models.CharField(max_length=50, unique=True)),
                ("department", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("is_cr_or_sic_member", models.BooleanField(default=False)),
                (
                    "attendance_current_semester",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "attendance_previous_year",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "cgpa",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("no_backlogs", models.BooleanField(default=True)),
                ("no_disciplinary_actions", models.BooleanField(default=True)),
                ("iut_participation", models.BooleanField(default=False)),
                ("sports_captain_or_coordinator", models.BooleanField(default=False)),
                ("is_hostel_resident", models.BooleanField(default=False)),
                (
                    "proof_document",
                    models.FileField(
                        blank=True, null=True, upload_to="candidate_proofs/"
                    ),
                ),
                ("manifesto", models.TextField()),
                ("dean_approved", models.BooleanField(default=False)),
                ("director_approved", models.BooleanField(default=False)),
                ("date_applied", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "position_applied",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elections.electionpost",
                    ),
                ),
            ],
        ),
    ]
