# Generated by Django 5.1.6 on 2025-02-20 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0002_voter_votecount"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="votecount",
            unique_together=set(),
        ),
        migrations.CreateModel(
            name="VoterVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elections.candidate",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elections.electionpost",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elections.voter",
                    ),
                ),
            ],
            options={
                "unique_together": {("voter", "post")},
            },
        ),
    ]
