# Generated by Django 5.1.6 on 2025-02-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_alter_votecount_unique_together_votervote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='registration_number',
            field=models.CharField(max_length=50),
        ),
    ]
