# Generated by Django 5.1.6 on 2025-02-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0003_alter_votecount_unique_together_votervote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="dean_approved",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="electionpost",
            name="dean_approved",
            field=models.BooleanField(default=True),
        ),
    ]
