<<<<<<< HEAD
# Generated by Django 5.1 on 2025-02-21 17:05
=======
# Generated by Django 5.1.6 on 2025-02-21 10:49
>>>>>>> ceafdc39d64a8762045cc3b4f1a58465973b7515

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("elections", "0004_alter_candidate_dean_approved_and_more"),
=======
        ('elections', '0004_alter_voter_registration_number'),
>>>>>>> ceafdc39d64a8762045cc3b4f1a58465973b7515
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="voter",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
=======
            model_name='voter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
>>>>>>> ceafdc39d64a8762045cc3b4f1a58465973b7515
        ),
    ]
