# Generated by Django 5.1.6 on 2025-02-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_alter_candidate_dean_approved_and_more'),
        ('elections', '0005_alter_voter_user'),
    ]

    operations = [
    ]
