# Generated by Django 5.1.6 on 2025-02-22 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0004_alter_voter_registration_number"),
        ("elections", "0006_merge_20250221_2152"),
    ]

    operations = []
