# Generated by Django 5.1.6 on 2025-02-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_merge_20250222_1113'),
        ('elections', '0007_merge_20250222_1128'),
    ]

    operations = [
    ]
