# Generated by Django 5.1.6 on 2025-02-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0007_merge_20250222_1113"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="votervote",
            unique_together={("post", "candidate")},
        ),
        migrations.AddField(
            model_name="electionpost",
            name="phase",
            field=models.CharField(
                choices=[("voting", "Voting Phase"), ("counting", "Counting Phase")],
                default="voting",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="votervote",
            name="voter",
        ),
    ]
