# Generated by Django 5.1.6 on 2025-02-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0007_merge_20250222_1128"),
        (
            "elections",
            "0008_alter_votervote_unique_together_electionpost_phase_and_more",
        ),
    ]

    operations = []
