# Generated by Django 5.1.6 on 2025-02-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_merge_20250222_2055'),
        ('elections', '0009_merge_20250222_2258'),
    ]

    operations = [
    ]
